import type { MenuData } from "./types";

/**
 * بيانات البداية (seed) اللي بتتحط في قاعدة البيانات أول مرة بس.
 * بعد كده مصدر الحقيقة هو الباك إند: أي تعديل من لوحة التحكم بيتحفظ في
 * جدول Supabase (أو ملف التطوير المحلي) ومنه بيقرأ كل العملاء.
 */
export const DEFAULT_DATA: MenuData = {
  version: 1,
  updatedAt: new Date(0).toISOString(),
  brand: {
    restaurantName: "مطعم البرجر الملكي",
    restaurantNameEn: "Royal Burger",
    tagline: "أسرع ديليفري وأعلى جودة",
    taglineEn: "Fastest delivery, best taste",
    logo: "",
    accent: "#f59e0b",
    theme: "dark",
    radius: 16,
    font: "cairo",
    language: "ar",
    showHero: true,
    heroImage:
      "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=1200&q=80",
    heroTitle: "طعم يخلّيك ترجع تاني 🔥",
    heroSubtitle: "اطلب بدقيقتين والطلب هيوصلك على باب البيت",
    announcementEnabled: true,
    announcementText: "🚚 توصيل مجاني للطلبات فوق ٣٠٠ ج.م — الكود: ROYAL",
  },
  contact: {
    whatsapp: "201000000000",
    phone: "0100 000 0000",
    address: "٢٧ شارع التسعين، التجمع الخامس، القاهرة",
    mapUrl: "https://maps.google.com/?q=Tasheen+St+Cairo",
    instagram: "https://instagram.com/",
    facebook: "",
    openingHours: "يومياً من ١٢ ظهراً حتى ٢ بعد منتصف الليل",
    isOpen: true,
    closedMessage: "المطعم مقفل حالياً.. اطلب بكرة الصبح 🌙",
    footerNote: "جميع الأصناف طازجة وتُحضّر عند الطلب — بالهنا والشفا 🍔",
  },
  commerce: {
    currency: "ج.م",
    currencyEn: "EGP",
    deliveryFee: 25,
    freeDeliveryOver: 300,
    minimumOrder: 80,
    serviceChargePercent: 0,
    orderTypes: ["delivery", "takeaway", "dinein"],
    requireName: true,
    requirePhone: true,
    requireAddress: true,
    enableNotes: true,
    enableSearch: true,
    enableFeatured: true,
    featuredLabel: "الأكثر طلباً ⭐",
    enableConfetti: true,
    showPrices: true,
    enableCart: true,
    orderTemplate: [
      "*طلب جديد — {restaurantName}* 🍔",
      "",
      "👤 *العميل:* {name}",
      "📞 *الموبايل:* {phone}",
      "🧾 *نوع الطلب:* {orderType}",
      "{addressLine}",
      "",
      "*تفاصيل الطلب:*",
      "{items}",
      "",
      "📝 *ملاحظات:* {notes}",
      "💰 *الإجمالي:* {total}",
    ].join("\n"),
  },
  categories: [
    { id: "c1", name: "برجر", nameEn: "Burgers", emoji: "🍔", visible: true },
    { id: "c2", name: "بيتزا", nameEn: "Pizza", emoji: "🍕", visible: true },
    { id: "c3", name: "مشاوي", nameEn: "Grills", emoji: "🍢", visible: true },
    { id: "c4", name: "مقبلات", nameEn: "Sides", emoji: "🍟", visible: true },
    { id: "c5", name: "مشروبات", nameEn: "Drinks", emoji: "🥤", visible: true },
    { id: "c6", name: "حلويات", nameEn: "Desserts", emoji: "🍮", visible: true },
  ],
  items: [
    {
      id: "i1",
      categoryId: "c1",
      name: "برجر السعادة دبل تشيز",
      nameEn: "Double Cheese Burger",
      description: "قطعتين لحم بلدي ٢٠٠ جرام مع صوص الشيدر السايح والبصل المكرمل",
      descriptionEn: "Two 200g beef patties, melted cheddar and caramelized onion",
      price: 180,
      oldPrice: 210,
      image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500&q=80",
      available: true,
      bestseller: true,
      isNew: false,
      spicy: 0,
      order: 1,
    },
    {
      id: "i2",
      categoryId: "c1",
      name: "سماش برجر كلاسيك",
      nameEn: "Classic Smash Burger",
      description: "شريحة لحم مقرمشة الأطراف مع صوص خاص وخيار مخلل",
      descriptionEn: "Crispy edge smash patty with house sauce and pickles",
      price: 150,
      oldPrice: null,
      image: "https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=500&q=80",
      available: true,
      bestseller: false,
      isNew: true,
      spicy: 0,
      order: 2,
    },
    {
      id: "i3",
      categoryId: "c1",
      name: "برجر الحارة تشيكن",
      nameEn: "Spicy Chicken Burger",
      description: "صدر دجاج متبل بصوص الحار مع هالبينو ومايونيز",
      descriptionEn: "Marinated chicken breast with hot sauce and jalapenos",
      price: 140,
      oldPrice: null,
      image: "https://images.unsplash.com/photo-1615297388948-e0437ba0e0a5?w=500&q=80",
      available: true,
      bestseller: false,
      isNew: false,
      spicy: 2,
      order: 3,
    },
    {
      id: "i4",
      categoryId: "c2",
      name: "بيتزا رانش باربيكيو",
      nameEn: "BBQ Ranch Pizza",
      description: "عجينة إيطالية خفيفة مع قطع الدجاج وصوص الرانش الغني",
      descriptionEn: "Thin Italian dough, chicken chunks and rich ranch sauce",
      price: 220,
      oldPrice: 260,
      image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=500&q=80",
      available: true,
      bestseller: true,
      isNew: false,
      spicy: 0,
      order: 1,
    },
    {
      id: "i5",
      categoryId: "c2",
      name: "بيتزا بيبروني",
      nameEn: "Pepperoni Pizza",
      description: "شرائح بيبروني مستوردة مع جبنة موزاريلا مضاعفة",
      descriptionEn: "Imported pepperoni with double mozzarella",
      price: 235,
      oldPrice: null,
      image: "https://images.unsplash.com/photo-1628840042765-356cda07504c?w=500&q=80",
      available: true,
      bestseller: false,
      isNew: false,
      spicy: 1,
      order: 2,
    },
    {
      id: "i6",
      categoryId: "c3",
      name: "كيلو كباب حلة مشكل",
      nameEn: "Mixed Grill Kilo",
      description: "كباب، كفتة، وشيش طاووق مع عيش بلدي وطحينة وسلطات",
      descriptionEn: "Kebab, kofta and tawook with bread, tahini and salads",
      price: 420,
      oldPrice: 480,
      image: "https://images.unsplash.com/photo-1544025162-d76694265973?w=500&q=80",
      available: true,
      bestseller: true,
      isNew: false,
      spicy: 0,
      order: 1,
    },
    {
      id: "i7",
      categoryId: "c3",
      name: "شيش طاووق",
      nameEn: "Shish Tawook",
      description: "قطع دجاج متبلة بالثوم والليمون مع صوص الثومية",
      descriptionEn: "Garlic-lemon marinated chicken with toum sauce",
      price: 175,
      oldPrice: null,
      image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=500&q=80",
      available: true,
      bestseller: false,
      isNew: false,
      spicy: 0,
      order: 2,
    },
    {
      id: "i8",
      categoryId: "c3",
      name: "ريش ضاني",
      nameEn: "Lamb Chops",
      description: "ريش طازجة على الفحم مع بهارات خاصة وبطاطس مشوي",
      descriptionEn: "Fresh charcoal-grilled lamb chops with roasted potatoes",
      price: 320,
      oldPrice: null,
      image: "https://images.unsplash.com/photo-1603360946369-dc940ce76d0a?w=500&q=80",
      available: false,
      bestseller: false,
      isNew: true,
      spicy: 0,
      order: 3,
    },
    {
      id: "i9",
      categoryId: "c4",
      name: "بطاطس كريسبي بالجبنة",
      nameEn: "Cheesy Crispy Fries",
      description: "أصابع بطاطس ذهبية مغطاة بجبنة شيدر وهالبينو",
      descriptionEn: "Golden fries loaded with cheddar and jalapenos",
      price: 65,
      oldPrice: 80,
      image: "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=500&q=80",
      available: true,
      bestseller: true,
      isNew: false,
      spicy: 1,
      order: 1,
    },
    {
      id: "i10",
      categoryId: "c4",
      name: "حلقات بصل مقرمشة",
      nameEn: "Crispy Onion Rings",
      description: "٩ حلقات بصل بpanko مقرمش مع صوص الرانش",
      descriptionEn: "Nine panko-breaded rings with ranch dip",
      price: 55,
      oldPrice: null,
      image: "https://images.unsplash.com/photo-1639024471283-03518883512d?w=500&q=80",
      available: true,
      bestseller: false,
      isNew: false,
      spicy: 0,
      order: 2,
    },
    {
      id: "i11",
      categoryId: "c5",
      name: "موهيتو فراولة وبلو بيري",
      nameEn: "Strawberry Mojito",
      description: "مشروب منعش بالليمون والنعناع والفواكه الطازجة",
      descriptionEn: "Refreshing lemon, mint and fresh berries",
      price: 55,
      oldPrice: null,
      image: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=500&q=80",
      available: true,
      bestseller: false,
      isNew: true,
      spicy: 0,
      order: 1,
    },
    {
      id: "i12",
      categoryId: "c5",
      name: "عصير برتقال طازج",
      nameEn: "Fresh Orange Juice",
      description: "كوب ٥٠٠ مل من البرتقال البلدي المعصور يومياً",
      descriptionEn: "500ml of freshly squeezed local oranges",
      price: 45,
      oldPrice: null,
      image: "https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=500&q=80",
      available: true,
      bestseller: false,
      isNew: false,
      spicy: 0,
      order: 2,
    },
    {
      id: "i13",
      categoryId: "c6",
      name: "كنافة بالقشطة",
      nameEn: "Kunafa with Cream",
      description: "كنافة ناعمة محشوة قشطة طازجة ومحمصة بالسمن البلدي",
      descriptionEn: "Soft kunafa stuffed with fresh cream",
      price: 90,
      oldPrice: 110,
      image: "https://images.unsplash.com/photo-1551024506-0bccd828d307?w=500&q=80",
      available: true,
      bestseller: true,
      isNew: false,
      spicy: 0,
      order: 1,
    },
    {
      id: "i14",
      categoryId: "c6",
      name: "تشيز كيك التوت",
      nameEn: "Berry Cheesecake",
      description: "قطعة تشيز كيك كريمة بصوص التوت الطازج",
      descriptionEn: "Creamy cheesecake with fresh berry sauce",
      price: 85,
      oldPrice: null,
      image: "https://images.unsplash.com/photo-1533134242443-d4fd215305ad?w=500&q=80",
      available: true,
      bestseller: false,
      isNew: false,
      spicy: 0,
      order: 2,
    },
  ],
};

/** مفتاح سلة العميل في متصفح الزائر — السلة بتتحول لطلب مسجّل في الباك إند */
export const CART_KEY = "royal-menu:cart:v1";
